name: Integration Test - Manual Scans
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration_tests_manual:
    name: Integration Test - Manual Scans
    runs-on: ubuntu-latest
    permissions:
      checks: write # Required for Publish Test Results
      pull-requests: write # Required for Publish Test Results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: 'python-version'

      - name: Cache pip dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: test
        run: |
          pytest --cov=manual_scans --cov=utils --cov-branch --cov-fail-under=18 --junitxml=test_reports/junit-integration.xml integration_tests/manual_scans

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          files: "test_reports/junit-integration.xml"
          check_name: "Integration Test Results - Manual Scans"
          comment_title: "Integration Test Results - Manual Scans"
