name: Integration Tests
on:
  push:

jobs:
  integration_tests:
    name: Integration Test
    runs-on: ubuntu-latest
    permissions:
      checks: write # Required for Publish Test Results
      pull-requests: write # Required for Publish Test Results
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: test
        run: |
          pytest --cov=manual_scans --cov=utils --cov-branch --cov-fail-under=19 --junitxml=test_reports/junit-integration.xml integration_tests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@82082dac68ad6a19d980f8ce817e108b9f496c2a # v2
        if: always()
        with:
          files: "test_reports/junit-integration.xml"
          check_name: "Integration Test Results"
          comment_title: "Integration Test Results"
