name: Integration Test - Manual Scans
on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration_tests_manual:
    name: Integration Test - Manual Scans
    runs-on: ubuntu-latest
    permissions:
      checks: write # Required for Publish Test Results
      pull-requests: write # Required for Publish Test Results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: 'python-version'

      - name: Cache pip dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: test
        run: |
          pytest --cov=manual_scans --cov=utils --cov-branch --cov-fail-under=18 --junitxml=test_reports/junit-integration.xml integration_tests/manual_scans

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          files: "test_reports/junit-integration.xml"
          check_name: "Integration Test Results - Manual Scans"
          comment_title: "Integration Test Results - Manual Scans"
