name: LocalStack
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.py"
      - "**/*.tf"
      - "**/*.txt"
      - ".github/workflows/localstack.yml"

jobs:
  localstack:
    name: Deploy
    runs-on: ubuntu-latest
    continue-on-error: true #temporary allow to fail
    defaults:
      run:
        shell: bash
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      TF_CLI_ARGS_plan: "-compact-warnings"
      TF_CLI_ARGS_apply: "-compact-warnings"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@a9b3e54ee0052a2f40a4eb4ca8b39dfd3bc2bc65 # v0.2.3
        with:
          image-tag: 'stable'
          install-awslocal: 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version-file: 'python-version'

      - name: Terraform-local installation
        run: pip install terraform-local virtualenv

      - name: terraform init
        run: tflocal init -backend-config=./integration_tests/localstack/backend.tflocalvars

      - name: terraform validate
        run: tflocal validate

      - name: terraform plan
        run: |
          tflocal plan -var-file=./integration_tests/localstack/domain-protect.tflocalvars -out=plan.tfplan

      - name: terraform apply
        run: tflocal apply -auto-approve plan.tfplan
