name: LocalStack
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.py"
      - "**/*.tf"
      - "**/*.txt"
      - ".github/workflows/localstack.yml"

jobs:
  localstack:
    name: Deploy
    runs-on: ubuntu-latest
    continue-on-error: true #temporary allow to fail
    defaults:
      run:
        shell: bash
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      TF_CLI_ARGS_plan: "-compact-warnings"
      TF_CLI_ARGS_apply: "-compact-warnings"
    steps:
      - uses: actions/checkout@v4

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.3
        with:
          image-tag: 'stable'
          install-awslocal: 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version-file: 'python-version'

      - name: Terraform-local installation
        run: pip install terraform-local virtualenv

      - name: terraform init
        run: tflocal init -backend-config=./integration_tests/localstack/backend.tflocalvars

      - name: terraform validate
        run: tflocal validate

      - name: terraform plan
        run: |
          tflocal plan -var-file=./integration_tests/localstack/domain-protect.tflocalvars -out=plan.tfplan

      - name: terraform apply
        run: tflocal apply -auto-approve plan.tfplan
