name: LocalStack
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.py"
      - "**/*.tf"
      - "**/*.txt"
      - ".github/workflows/localstack.yml"

jobs:
  localstack:
    name: Deploy
    runs-on: ubuntu-latest
    continue-on-error: true #temporary allow to fail
    defaults:
      run:
        shell: bash
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      TF_CLI_ARGS_plan: "-compact-warnings"
      TF_CLI_ARGS_apply: "-compact-warnings"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@9392b05ddb345894c2e86305fc426566e738c1db # v0.2.4
        with:
          image-tag: 'stable'
          install-awslocal: 'true'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version-file: 'python-version'

      - name: Terraform-local installation
        run: pip install terraform-local virtualenv

      - name: terraform init
        run: tflocal init -backend-config=./integration_tests/localstack/backend.tflocalvars

      - name: terraform validate
        run: tflocal validate

      - name: terraform plan
        run: |
          tflocal plan -var-file=./integration_tests/localstack/domain-protect.tflocalvars -out=plan.tfplan

      - name: terraform apply
        run: tflocal apply -auto-approve plan.tfplan
