name: Formatting and Unit Tests
on:
  push:

env:
  TERRAFORM_DOCS_VERSION: v0.19.0
  TERRAFORM_VERSION: "1.7.3"

permissions:
  contents: read

jobs:
  unit_tests:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      checks: write # Required for Publish Test Results
      pull-requests: write # Required for Publish Test Results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: 'python-version'

      - name: Cache pip dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: pip install -r requirements-dev.txt

      - name: Install terraform-docs
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: terraform-docs/terraform-docs
          tag: ${{ env.TERRAFORM_DOCS_VERSION }}

      - name: Cache pre-commit environments
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Linting and formatting
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Unit tests
        run: |
          pytest --cov=manual_scans --cov=utils --cov-branch --cov-fail-under=15 unittests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          files: "test_reports/*.xml"
